name: zjsb_app
description: A new Flutter application.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  #sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #使用PackageInfo查询有关应用程序包的信息。这适用于iOS和Android。
  package_info: 2.0.0
  #RSA AES加密
  encrypt: 5.0.0
  #各种滚动选择器  时间，数字，文字
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  # 刷新 flutter_easyrefresh  https://pub.flutter-io.cn/packages/flutter_easyrefresh
  flutter_easyrefresh: 2.2.1
  # 图片查看 photo_view:  https://pub.flutter-io.cn/packages/photo_view
  photo_view: 0.11.1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: 3.0.0
  # 网络库 https://github.com/flutterchina/dio
  dio: 4.0.0
  # https://github.com/ReactiveX/rxdart
  rxdart: 0.26.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 2.0.1
  # Flutter shared_preferences plugin util https://github.com/Sky24n/sp_util
  sp_util: 2.0.3
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.3
  # 图片选择插件
  wechat_assets_picker: 5.5.7
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: 0.6.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: 3.4.0
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: 0.2.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: 2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: 3.0.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: 6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: 5.0.0
  # 高德地图
  #    amap_flutter_map: 2.0.1
  # 定位
  #    amap_flutter_location: 2.0.0
  #权限管理
  permission_handler: 7.0.0
  #有一种自下而上的方法来构建小部件,解决嵌套过深的问题
  styled_widget: 0.3.0
  # WebView插件  支持设置宽高， 官方的只能全屏
  flutter_inappwebview: 5.3.2
  flutter_page_indicator: 0.0.3
  transformer_page_view: 0.1.6
  #保存图片到本地
  image_gallery_saver: 1.6.9
  #生成二维码
  qr_flutter: 4.0.0
  #扫描二维码
  scan: 1.4.3
  #验证码
  flutter_verification_box: 2.0.0
  #Fluwx是WeChatSDK的flutter插件 分带支付和不带支付的
  fluwx_no_pay: 3.4.3
  connectivity: ^3.0.6
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  #日志打印
  flutter_easylogger: ^2.3.0
  #骨架屏
  pk_skeleton: ^0.0.2
  #电话时区
  intl_phone_number_input: ^0.7.0+2
  #屏幕适配
  flutter_screenutil: ^5.0.0+2
  #数据序列化
  json_annotation: ^4.0.0
  #loading提示弹窗
  flutter_easyloading: ^3.0.3
  

dev_dependencies:
  # Widget测试
  flutter_test:
    sdk: flutter
  # 单元测试
  test: ^1.15.2
  #数据序列化
  build_runner: ^1.0.0
  json_serializable: ^4.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
  #    - assets/images/2.0x/
  #    - assets/images/3.0x/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true



